name: JailBreakTester
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.14
  - pip
  - pip:
      - Flask==3.0.3
      - litellm==1.50.2
      - matplotlib==3.8.3
      - numpy
      - ollama==0.3.3
      - PyQt5==5.15.11
      - PyQt5_sip==12.15.0
      - Requests==2.32.3
      - scikit_learn==1.4.1.post1
      - sentence_transformers==2.6.1
      - transformers==4.44.2
      - llama-cpp-python==0.3.1

